name: meme_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_test: ^9.1.3
  card_swiper: ^2.0.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  json_annotation: ^4.8.1
  line_icons: ^2.0.3
  mockito: ^5.4.2
  shimmer: ^3.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/images/

  uses-material-design: true
